# Generated by Django 5.0.7 on 2024-08-10 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("version", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "curso",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=50)),
                ("numero", models.CharField(max_length=10)),
                ("dpto", models.CharField(blank=True, max_length=10, null=True)),
                ("comuna", models.CharField(max_length=50)),
                ("ciudad", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "direccion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_nac", models.DateField()),
                ("activo", models.BooleanField(blank=True, null=True)),
                ("creacion_registro", models.DateField(blank=True, null=True)),
                ("modificacion_registro", models.DateField(blank=True, null=True)),
                ("creado_por", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "estudiante",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("activo", models.BooleanField(blank=True, null=True)),
                ("creacion_registro", models.DateField(blank=True, null=True)),
                ("modificacion_registro", models.DateField(blank=True, null=True)),
                ("creado_por", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "profesor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EstudianteCurso",
            fields=[
                (
                    "estudiante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="web.estudiante",
                    ),
                ),
            ],
            options={
                "db_table": "estudiante_curso",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProfesorCurso",
            fields=[
                (
                    "profesor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="web.profesor",
                    ),
                ),
            ],
            options={
                "db_table": "profesor_curso",
                "managed": False,
            },
        ),
    ]
